library(shiny)
library(shinydashboard)
library(leaflet)
library(googleVis)
library(dplyr)
library(shinythemes)
library(ggplot2)
library(ggthemes)
library(dygraphs)
library(xts)
library(RColorBrewer)
mel_airbnb <- read.csv("listings.csv")
review <- read.csv("reviews_dec18.csv")
#mel_airbnb$room_type <- as.factor(mel_airbnb$room_type)
pal <- colorFactor(c("#EE3B3B", "#0000EE","#66CD00"), domain = c("Entire home/apt", "Private room","Shared room"))
council <- sort(unique(mel_airbnb$neighbourhood))
choice=names(review)[-c(1:3)]
room_types <- c("Entire home/apt", "Private room","Shared room")
